apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-pv
  labels:
    type: local
    app: spark
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/k8s/spark/data
  persistentVolumeReclaimPolicy: Recycle
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["worker208-1"]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc
spec:
  volumeName: spark-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
