apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawl-info-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Big-data-service
  template:
    metadata:
      labels:
        app: Big-data-service
    spec:
      containers:
      - name: crawl-info-deployment
        image: 21521490/crawl-review-product
        env:
        - name: BOOTSTRAP_SERVERS
          value: $IP_KAFKA_BROKER
        - name: GROUP_ID_INFO
          value: product-review-group
