apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  selector:
    app: api-service
  ports:
  - name: api
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  externalIPs:
  - 10.10.10.245

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api
        image: caothi/api_bigdata
        ports:
        - containerPort: 5000
          name: api
